Fix Partial Program Crash BUG
Fixed a bug that caused the game to crash when downloading certain modifiers.

Corresponding error message:
UnboundLocalError: local variable 'gameRawName' referenced before assignment