Bug Fixes
Error 1:
File "Game-Cheats-Manager\helper.py", line 1209
trainerDisplayName = f"{entry["en_name"]} Trainer"
SyntaxError: f-string: unmatched '['

Needed to be changed to single quotes.

Error 2:
File "Game-Cheats-Manager\helper.py", line 1211
    trainerDisplayName = f"《{re.sub(r"\s(v[\d\.v\-]+.*|Early ?Access.*)", "", entry["title"])}》修改器"
SyntaxError: unexpected character after line continuation character

Placing the regular expression and other text in the same line of code caused a strange formatting error, so I extracted the regular expression separately: pattern = r'\s(v[\d.v-]+.|Early ?Access.)'